### ISSUE TITLE
API Utils

### ISSUE THREAD

**Issue by aube-dev** [manyaak/manyaak-front#10]
## 👩‍💻 Summary

API 호출을 위한 util code base를 작성한다.

## 📄 Description

API 호출 시 일관되고 편리한 코드 작성을 위해 여러 유틸 코드를 작성하려고 한다.
- method, endpoint, request schema 등 다양한 정보를 받아 API fetcher를 반환하는 유틸
- access token, error alert 등을 관리하는 fetcher wrapper custom hook
- React Query를 더 편리하게 이용할 수 있는 wrapper custom hook

## ✅ Todo

- [x] `getApi` 구현
- [x] `useAuth`, `useGlobalAlert`, `useApi` 구현
- [x] `useApiQuery`, `useApiMutation`, `useApiInfiniteQuery` 구현
- [x] 테스트 페이지 작성
