### ISSUE TITLE
API 연결

### ISSUE THREAD

**Issue by aube-dev** [manyaak/manyaak-front#14]
## 👩‍💻 Summary

개발된 UI에 API를 연결하여 실제 동작이 가능하도록 한다.

## 📄 Description

현재 완성된 페이지 UI에 API를 연결하고 비즈니스 로직을 추가한다.
다만 아직 작업되지 않은 UI도 있으므로 이전 작업이 완료되면 처리한다.

## ✅ Todo

- [ ] 친구 탭 API 연결
- [ ] 약속 탭 API 연결
- [ ] 약속 요청 플로우 API 연결
- [ ] 홈 화면 API 연결
